export const AUTHENTICATE_THE_USER = 'AUTHENTICATE_THE_USER'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'


export const ARTICLE_GET_TAG_LIST = 'ARTICLE_GET_TAG_LIST'
export const ARTICLE_GET_CATEGORY_LIST = 'ARTICLE_GET_CATEGORY_LIST'
